try:
    from ...config.error import ColumnError
except ImportError:
    from emscan.config.error import ColumnError
from typing import Iterable


Columns = {
    "ECU":{
        "other_names": ["ecu", "controller", "sender", "tx", "송출제어기"],
        "display_name": "ECU",
        "show_on_html": True,
        "property": "common",
        "dtype": str,
        "width": 100,
        "align": "center",
    },
    "Message":{
        "other_names": ["message", "msg"],
        "display_name": "Message",
        "show_on_html": True,
        "property": "common",
        "dtype": str,
        "width": 140,
        "align": "center",
    },
    "ID":{
        "other_names": ["id"],
        "display_name": "ID",
        "show_on_html": True,
        "property": "common",
        "dtype": str,
        "width": 60,
        "align": "center",
    },
    "DLC":{
        "other_names": ["dlc"],
        "display_name": "DLC",
        "show_on_html": True,
        "property": "message",
        "dtype": int,
        "width": 30,
        "align": "center",
    },
    "Send Type":{
        "other_names": ["sendtype"],
        "display_name": "Send Type",
        "show_on_html": True,
        "property": "message",
        "dtype": str,
        "width": 30,
        "align": "center",
    },
    "Cycle Time":{
        "other_names": ["cycletime"],
        "display_name": "Cycle Time",
        "show_on_html": True,
        "property": "common",
        "dtype": int,
        "width": 30,
        "align": "center",
    },
    "Signal":{
        "other_names": ["signal", "sig"],
        "display_name": "Signal",
        "show_on_html": True,
        "property": "signal",
        "dtype": str,
        "width": 200,
        "align": "left",
    },
    "Definition":{
        "other_names": ["definition"],
        "display_name": "Definition",
        "show_on_html": False,
        "property": "signal",
        "dtype": str,
        "width": 240,
        "align": "left",
    },
    "Length":{
        "other_names": ["length", "Length\n(Bit)"],
        "display_name": "Length",
        "show_on_html": True,
        "property": "signal",
        "dtype": int,
        "width": 30,
        "align": "center",
    },
    "StartBit":{
        "other_names": ["startbit", "Startbit", "address"],
        "display_name": "Start Bit",
        "show_on_html": True,
        "property": "signal",
        "dtype": int,
        "width": 30,
        "align": "center",
    },
    "Sig Receivers":{
        "other_names": ["Destination", "receiver"],
        "display_name": "Receivers",
        "show_on_html": False,
        "property": "signal",
        "dtype": str,
        "width": 80,
        "align": "left",
    },
    "UserSigValidity":{
        "other_names": [],
        "display_name": "User Validity",
        "show_on_html": True,
        "property": "signal",
        "dtype": str,
        "width": 60,
        "align": "center",
    },
    "Value Table":{
        "other_names": ["table"],
        "display_name": "Table",
        "show_on_html": False,
        "property": "signal",
        "dtype": str,
        "width": 140,
        "align": "left",
    },
    "Value Type":{
        "other_names": ["type"],
        "display_name": "Type",
        "show_on_html": True,
        "property": "signal",
        "dtype": str,
        "width": 80,
        "align": "center",
    },
    "GenSigStartValue":{
        "other_names": ["startvalue", "initialValue", "initial"],
        "display_name": "Init Value",
        "show_on_html": True,
        "property": "signal",
        "dtype": str,
        "width": 80,
        "align": "center",
    },
    "Factor":{
        "other_names": ["factor"],
        "display_name": "Factor",
        "show_on_html": True,
        "property": "signal",
        "dtype": float,
        "width": 60,
        "align": "center",
    },
    "Offset":{
        "other_names": ["offset"],
        "display_name": "Offset",
        "show_on_html": True,
        "property": "signal",
        "dtype": float,
        "width": 60,
        "align": "center",
    },
    "Min":{
        "other_names": ["min"],
        "display_name": "Min",
        "show_on_html": False,
        "property": "signal",
        "dtype": float,
        "width": 60,
        "align": "center",
    },
    "Max":{
        "other_names": ["max"],
        "display_name": "Max",
        "show_on_html": False,
        "property": "signal",
        "dtype": float,
        "width": 60,
        "align": "center",
    },
    "Unit":{
        "other_names": ["unit"],
        "display_name": "Unit",
        "show_on_html": True,
        "property": "signal",
        "dtype": str,
        "width": 60,
        "align": "center",
    },
    "Local Network Wake Up Request":{
        "other_names": [],
        "display_name": "Wake Up Request",
        "show_on_html": True,
        "property": "message",
        "dtype": str,
        "width": 40,
        "align": "center",
    },
    "Network Request Holding Time":{
        "other_names": [],
        "display_name": "Request Holding Time",
        "show_on_html": False,
        "property": None,
        "dtype": str,
        "width": 30,
        "align": "center",
    },
    "Description":{
        "other_names": ["description"],
        "display_name": "Description",
        "show_on_html": False,
        "property": "signal",
        "dtype": str,
        "width": 100,
        "align": "left",
    },
    "Version":{
        "other_names": ["version"],
        "display_name": "Version",
        "show_on_html": False,
        "property": "signal",
        "dtype": str,
        "width": 80,
        "align": "center",
    },
    "Timeout": {
        "other_names": [],
        "display_name": "Timeout",
        "show_on_html": False,
        "property": "message",
        "dtype": str,
        "width": 80,
        "align": "center",
    },
    "ByteOrder": {
        "other_names": [],
        "display_name": "Order",
        "show_on_html": True,
        "property": "message",
        "dtype": str,
        "width": 80,
        "align": "center",
    },
    "ICE Channel":{
        "other_names": [],
        "display_name": "ICE Channel",
        "show_on_html": True,
        "property": "message",
        "dtype": str,
        "width": 60,
        "align": "center",
    },
    "ICE WakeUp":{
        "other_names": [],
        "display_name": "ICE WakeUp",
        "show_on_html": True,
        "property": "message",
        "dtype": str,
        "width": 60,
        "align": "center",
    },
    "HEV Channel":{
        "other_names": [],
        "display_name": "HEV Channel",
        "show_on_html": True,
        "property": "message",
        "dtype": str,
        "width": 60,
        "align": "center",
    },
    "HEV WakeUp": {
        "other_names": [],
        "display_name": "HEV WakeUp",
        "show_on_html": True,
        "property": "message",
        "dtype": str,
        "width": 60,
        "align": "center",
    },
    "SystemConstant":{
        "other_names": [],
        "display_name": "Syscon",
        "show_on_html": True,
        "property": "message",
        "dtype": str,
        "width": 160,
        "align": "center",
    },
    "Codeword":{
        "other_names": [],
        "display_name": "Codeword",
        "show_on_html": True,
        "property": "message",
        "dtype": str,
        "width": 160,
        "align": "center",
    },
    "Formula":{
        "other_names": [],
        "display_name": "Formula",
        "show_on_html": True,
        "property": "signal",
        "dtype": str,
        "width": 140,
        "align": "center",
    },
    "SignedProcessing":{
        "other_names": [],
        "display_name": "Signed Process",
        "show_on_html": True,
        "property": "signal",
        "dtype": str,
        "width": 100,
        "align": "center",
    },
    "InterfacedVariable":{
        "other_names": [],
        "display_name": "Internal Variable",
        "show_on_html": True,
        "property": "signal",
        "dtype": str,
        "width": 200,
        "align": "left",
    },
    "SignalRenamed":{
        "other_names": [],
        "display_name": "Renamed",
        "show_on_html": True,
        "property": "signal",
        "dtype": str,
        "width": 200,
        "align": "left",
    },
    "History":{
        "other_names": [],
        "display_name": "History",
        "show_on_html": False,
        "property": "signal",
        "dtype": str,
        "width": 100,
        "align": "center",
    },
    "Remark":{
        "other_names": [],
        "display_name": "Remark",
        "show_on_html": False,
        "property": "signal",
        "dtype": str,
        "width": 100,
        "align": "center",
    }
}

def autofix(columns:Iterable) -> list:
    new_columns = []
    for col in Columns:
        if col in columns:
            new_columns.append(col)
            continue
        for other in Columns[col]["other_names"]:
            if other in columns:
                new_columns.append(col)
        if not col in new_columns:
            raise ColumnError(f"Cannot find {col} in columns; {columns}")
    return new_columns

def jss(columns:Iterable) -> list:
    cols = []
    for col in columns:
        if not col in Columns:
            cols.append({"type": "text", "width": 100})
        else:
            attr = Columns[col]
            cols.append({"type": "text", "width": attr["width"], "title":col, "align": attr["align"]})
    return cols

